//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakerspaceWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaAssignments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AreaAssignments()
        {
            this.IsSteward = false;
        }
    
        public int AreaAssignmentId { get; set; }
        public int AreaId { get; set; }
        public int MemberId { get; set; }
        public bool IsSteward { get; set; }
    
        public virtual Areas Area { get; set; }
        public virtual Members Member { get; set; }
    }
}
