//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakerspaceWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MakerModelContainer : DbContext
    {
        public MakerModelContainer()
            : base("name=MakerModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Classes> Classes { get; set; }
        public virtual DbSet<Credits> Credits { get; set; }
        public virtual DbSet<AreaAssignments> AreaAssignments { get; set; }
    }
}
